#!/usr/bin/env bash

if
  [[ -s "/home/ubuntu/.rvm/gems/ruby-2.4.1/environment" ]]
then
  source "/home/ubuntu/.rvm/gems/ruby-2.4.1/environment"
  exec rails "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/ubuntu/.rvm/gems/ruby-2.4.1/environment'" >&2
  exit 1
fi
